idaas:
  id: ${CIBIS_CONSUMER_INTEGRATION_ID}
  version: "2"
  url: "https://eag-dev.aexp.com/oneidentity/security/digital/v1/application/token"
  secret: ${CIBIS_CONSUMER_SECRET}
  token_refresh_time: 60
  verify_ssl: false

llm:
  url: "https://eag-dev.aexp.com/genai/google/v1/models/gemini-1.5-pro-002/generateContent"
  scope: ["/genai/google/v1/models/gemini-1.5-pro-002/#*::post"]
  temperature: 0.5
  top_k: 5
  top_p: 0.9
  max_tokens: 1024
  verify_ssl: false

mcp:
  servers:
    looker:
      url: "http://localhost:5000/mcp"
      transport: "streamable-http"
      verify_ssl: false
