idaas:
  url: "https://oneidentityapi-dev.aexp.com/security/digital/v1/application/token"
  scope:
    - "/genai/google/v1/models/gemini-2.5-pro/#*::post"
  originator_source: "digital-payments"
  id: ${CIBIS_CONSUMER_INTEGRATION_ID}
  secret: ${CIBIS_CONSUMER_SECRET}
  token_refresh_interval: 60
  verify_ssl: false

llm:
  url: "https://eag-dev.aexp.com/genai/google/v1/models/gemini-2.5-pro/generateContent"
  temperature: 0.5
  top_k: 5
  top_p: 0.9
  max_tokens: 1024
  verify_ssl: false

mcp:
  servers:
    looker:
      url: "http://127.0.0.1:5001/mcp"
      transport: "streamable-http"
      verify_ssl: false
